use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use schemars::schema_for;
use seis_contracts_core::{
    DatasetId, InterpretationPoint, ProcessingParameters, SectionAxis, SectionRequest,
    SectionTileRequest, VolumeDescriptor,
};
use seis_contracts_interop::{PreviewCommand, PreviewResponse, IPC_SCHEMA_VERSION};
use seis_contracts_views::{PreviewView, SectionView};
use ts_rs::TS;

fn main() -> Result<(), Box<dyn Error>> {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("scripts/contracts-export should live two levels under repo root")
        .to_path_buf();

    let package_root = repo_root.join("contracts").join("ts").join("seis-contracts");
    let generated_dir = package_root.join("src").join("generated");
    let schema_dir = package_root.join("schemas");

    fs::create_dir_all(&generated_dir)?;
    fs::create_dir_all(&schema_dir)?;

    export_ts_types(&generated_dir)?;
    write_generated_index(&generated_dir)?;
    write_schema_bundle(&schema_dir)?;

    Ok(())
}

fn export_ts_types(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    for file in [
        "DatasetId.ts",
        "VolumeDescriptor.ts",
        "SectionAxis.ts",
        "SectionRequest.ts",
        "SectionTileRequest.ts",
        "ProcessingParameters.ts",
        "InterpretationPoint.ts",
        "SectionView.ts",
        "PreviewView.ts",
        "PreviewCommand.ts",
        "PreviewResponse.ts",
        "ipc-schema-version.ts",
        "index.ts",
    ] {
        let path = output_dir.join(file);
        if path.exists() {
            fs::remove_file(path)?;
        }
    }

    VolumeDescriptor::export_all_to(output_dir)?;
    SectionTileRequest::export_all_to(output_dir)?;
    ProcessingParameters::export_all_to(output_dir)?;
    InterpretationPoint::export_all_to(output_dir)?;
    PreviewCommand::export_all_to(output_dir)?;
    PreviewResponse::export_all_to(output_dir)?;

    fs::write(
        output_dir.join("ipc-schema-version.ts"),
        format!(
            "// Generated by `cargo run -p contracts-export`\nexport const IPC_SCHEMA_VERSION = {IPC_SCHEMA_VERSION} as const;\n"
        ),
    )?;

    Ok(())
}

fn write_generated_index(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let index = r#"// Generated by `cargo run -p contracts-export`
export type { DatasetId } from "./DatasetId";
export type { VolumeDescriptor } from "./VolumeDescriptor";
export type { SectionAxis } from "./SectionAxis";
export type { SectionRequest } from "./SectionRequest";
export type { SectionTileRequest } from "./SectionTileRequest";
export type { ProcessingParameters } from "./ProcessingParameters";
export type { InterpretationPoint } from "./InterpretationPoint";
export type { SectionView } from "./SectionView";
export type { PreviewView } from "./PreviewView";
export type { PreviewCommand } from "./PreviewCommand";
export type { PreviewResponse } from "./PreviewResponse";
export { IPC_SCHEMA_VERSION } from "./ipc-schema-version";
"#;

    fs::write(output_dir.join("index.ts"), index)?;
    Ok(())
}

fn write_schema_bundle(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let bundle = serde_json::json!({
        "ipcSchemaVersion": IPC_SCHEMA_VERSION,
        "types": {
            "DatasetId": schema_for!(DatasetId),
            "VolumeDescriptor": schema_for!(VolumeDescriptor),
            "SectionAxis": schema_for!(SectionAxis),
            "SectionRequest": schema_for!(SectionRequest),
            "SectionTileRequest": schema_for!(SectionTileRequest),
            "ProcessingParameters": schema_for!(ProcessingParameters),
            "InterpretationPoint": schema_for!(InterpretationPoint),
            "SectionView": schema_for!(SectionView),
            "PreviewView": schema_for!(PreviewView),
            "PreviewCommand": schema_for!(PreviewCommand),
            "PreviewResponse": schema_for!(PreviewResponse),
        }
    });

    fs::write(
        output_dir.join("seis-contracts.schema.json"),
        serde_json::to_string_pretty(&bundle)?,
    )?;

    Ok(())
}
